#!/usr/bin/env python3
"""Inject Marp speaker notes (HTML comments) into all slide decks.

Notes are keyed to the first heading found in each slide block.
Each note goes immediately before the closing `---` of a slide.
"""
import re, os, sys

BASE = os.path.join(os.path.dirname(__file__), '..', 'docs', 'slides')

# ---------------------------------------------------------------------------
# Note data: { filename_stem: { heading_text: note_html } }
# heading_text is matched against the *first* heading in each slide block
# using `in` (substring match), case-sensitive.
# The fallback key '' is used when no heading matches.
# ---------------------------------------------------------------------------

ZH = {
    '01-course-intro': {
        '軟體測試視覺化系列': '歡迎學生。本系列共 13 講，每講都有一個可在瀏覽器直接操作的互動工具，目標是讓抽象準則變成可量化的工程實踐。',
        '課程目標': '強調「動手做」：每個 requirement 是工具裡可點選的項目，學生能即時看到覆蓋率數字如何變化，而不只是背定義。',
        '課程地圖': '課程現已擴展為 13 講（含 Data Flow #4 與 Logic Binding #13）。三條主線：圖（#3–#4）、邏輯（#5、#13）、突變（#6–#8）。',
        '學習依賴': '三條子線可不按順序修，但 Graph Coverage 是 Data Flow 的前置知識。可問學生：你目前在哪一條路線上？',
        '三大分類': '「程式碼可見度」是本課分類的核心軸。問學生日常測試屬於哪一類——往往答案是灰盒，引導他們思考為什麼。',
        '黑盒': 'BVA 最容易被低估但效果顯著。強調這四種技巧不需要看原始碼，可以在需求評審會議就開始設計測試。',
        '白盒': '白盒的核心心智：「有結構就能定義覆蓋準則」。後續每講深入一種結構（圖、邏輯、突變），這些技巧都是這句話的具體化。',
        '灰盒': '問學生：有沒有人完整看過所有 dependency 的原始碼？這個問題通常讓大家意識到現實中幾乎都是灰盒。',
        '工具：測試方法樹': '現場打開工具，先按 toggle-all-btn 展開全部 16 種技巧，再請學生找到 visibility-fill 進度條並說出黑盒是 0%。',
        '工具：白盒展開後': '特別指出 symbex 和 concolic——業界用於自動測試生成的高端技術，後面第 10–11 講會深入介紹。',
        '觀念支點': '這三個心智模型（抽象、覆蓋、突變）是整個系列的骨架。每個準則都能歸入其中一類，這是整理知識的好框架。',
        '小結': '本講是概覽，不需要全部記住。重要的是知道「有這些分類和工具存在」，後續各講會逐一深入每個準則。',
        '課堂練習': '預留 10–15 分鐘操作工具。練習 1 最基本（找技巧），練習 3 適合作課後討論（灰盒 API 測試）。',
        '進一步閱讀': '有興趣的同學可讀 A&O §1–2。工具完整設計決策在 docs/Specification.zh-TW.md。',
    },
    '02-testing-flow-pyramid': {
        '測試流程': '本講串聯「流程」與「金字塔」兩個視角，讓學生理解測試不只是「執行程式看有沒有 crash」，而是有完整的工程週期。',
        '兩條主線': '強調兩個視角互補：流程告訴你「什麼時候做什麼」，金字塔告訴你「各層測試的比例」。',
        '測試流程：六個步驟': '六步驟的核心是「可重複」：每次改完 code 都能跑一遍，而不是只在 release 前做一次。',
        '工具：自動播放流程': '現場開工具，按 auto-play 讓六步驟自動輪播。讓學生觀察每個步驟的說明文字，找出哪個步驟他們最常略過。',
        '為什麼這條流程仍重要': '即使有 CI/CD，這六步驟的邏輯仍在。CI/CD 只是讓流程自動化，不是讓流程消失。',
        '換個觀點：測試金字塔': '金字塔最重要的洞見：單元測試應該是最多的，E2E 測試應該是最少的，因為速度和成本的差異。',
        '四層測試類型': '可問學生：你的專案金字塔長什麼樣？是不是倒三角形（大量 E2E、很少單元測試）？',
        '工具：金字塔 + 卡片': '工具裡的金字塔是互動的——點擊各層會展開說明卡片。請學生點擊看看每層的例子。',
        '經典原則：Test Pyramid': 'Mike Cohn 的金字塔原則被廣泛引用，但現實中很多團隊做反了。問學生為什麼 E2E 測試不應該是主力。',
        '兩種反金字塔陷阱': '冰淇淋甜筒和沙漏模型都是常見的反模式。可以問學生他們的專案是哪種形狀，討論如何改善。',
        '把兩個視角連在一起': '關鍵連結：六步驟中的「Test Design」對應金字塔的選層決策——要先想好在哪一層測，再設計測試案例。',
        '小結': '本講的核心：流程讓測試有序，金字塔讓資源分配合理。兩者缺一不可。',
        '課堂練習': '練習 1 最重要（畫出自己的金字塔）。練習 3 的 CI/CD 討論可引導學生思考自動化的邊界。',
        '進一步閱讀': 'Fowler 的部落格文章「TestPyramid」是這個概念的最佳二手資源，短而精確。',
    },
    '03-graph-coverage': {
        'Graph Coverage': '本講是整個系列的圖論基礎。學生先掌握這裡的 CFG 與覆蓋準則，後續的 Data Flow、Test Generation 才能順暢銜接。',
        '為什麼是 Graph Coverage': 'CFG 是從程式到可計算覆蓋準則的橋梁。強調：不只 if/while，任何有「流」的結構都可以建圖。',
        '抽象：什麼是 CFG': 'Node = 基本塊（basic block），Edge = 控制流轉移。可以現場白板畫一個簡單的 if-else CFG，讓學生參與填 node。',
        '五條結構性覆蓋準則': '這五條準則有嚴格的 subsumption 階梯。強調 Prime Path Coverage 是這裡的「王者」，能包含大部分下層準則。',
        'Subsumption 關係': 'Subsumption 圖是理解準則強弱的關鍵工具。可以問：為什麼 Edge Coverage 不蘊含 Prime Path Coverage？',
        '教科書範例：sample CFG': '這個 sample CFG 是 Ammann & Offutt 教科書的標準範例。請學生先手算 NC 再對答案，建立計算直覺。',
        '手算：Node Coverage': 'NC 只需要每個 node 至少被一條 test path 通過一次。請學生試著找出最少測試路徑數。',
        '手算：Edge Coverage': 'EC 需要每條 edge 至少被覆蓋一次。常常只需要比 NC 多一到兩條路徑。',
        '手算：Prime Path Coverage': 'PPC 需要找出所有 prime paths（不重複自己的最長簡單路徑）。強調這可能比 TC 少，因為不用覆蓋所有路徑。',
        '工具演示：選 criterion': '現場打開工具，選 Node Coverage，讓工具算出需求列表。觀察需求數量如何隨準則升高而增加。',
        '工具演示：metrics 與 greedy set cover': '工具用 greedy set cover 找最少測試集。問學生：這個貪婪解是否保證最優？（不保證，但通常很接近。）',
        '工具演示：上傳程式碼': '讓學生上傳自己寫的簡單函式，看工具如何自動生成 CFG。提醒工具只處理 JavaScript 函式語法。',
        '即時編輯 CFG': '即時編輯模式讓學生直接修改 dot 格式的 CFG，適合手動建構教科書範例。',
        '小結': 'CFG + 五條準則是本系列的圖論骨幹。掌握這裡，Data Flow（#4）和 Test Generation（#12）自然銜接。',
        '課堂練習': '練習 1（手算 prime paths）最重要，建議現場完成。練習 3（上傳自己程式）適合作作業。',
        '進一步閱讀': 'A&O §3 有完整的 CFG 理論。工具裡的 prime path 演算法可以在 src/utils/graphCoverage.js 看到實作細節。',
    },
    '04-data-flow-coverage': {
        'Data Flow Coverage': '本講把 CFG 延伸到「資料流」，從結構走到語意。掌握 def/use 對的定義是整個講次的核心。',
        '從結構走到資料': 'CFG 只看「走哪條邊」，DFC 還要看「變數在哪裡被賦值、在哪裡被使用」。這讓測試能捕捉更多語意錯誤。',
        '三個核心概念': 'def-clear path 是最重要的概念：從 def 到 use 的路徑上，如果變數沒有被重新賦值，才算是有效的 def-use 對。',
        '三條資料流覆蓋準則': 'All-Defs < All-Uses < All-DU-Paths 的強弱順序。All-Uses 是最常在實務中被採用的準則。',
        'Subsumption（結構 + 資料流）': '資料流覆蓋和結構覆蓋的 subsumption 關係交錯。All-Uses 包含 Edge Coverage，這是個重要但不直觀的結論。',
        '教科書範例：來自 Triangle Problem': 'Triangle Problem 是 Ammann & Offutt 的標準範例。讓學生先手工找出所有 def/use 對，再與工具比對。',
        'def / use 抽取規則': '可賦值語句（=）和函式參數是最常見的 def 點；條件判斷和運算元是最常見的 use 點。',
        '工具演示：DFG 視圖': '工具的 DFG 視圖把 CFG 的每個 node 展開成 def 點和 use 點。讓學生觀察箭頭如何連接 def 到 use。',
        '工具演示：All-Defs': 'All-Defs 只需要每個 def 至少走到一個 use。這是最弱的資料流準則，通常需求數最少。',
        '工具演示：All-Uses': 'All-Uses 要求每個 def-use 對都被測試。可以問：如果一個 def 有 5 個 use，需要幾條 test path？',
        '工具演示：All-DU-Paths': 'All-DU-Paths 是最強的資料流準則，需要覆蓋每個 def-use 對的每一條 def-clear path。通常測試集很大。',
        'DFG 為何可能是空的': '如果函式沒有變數賦值（只有 return 語句），DFG 會是空的。這是工具的設計選擇，不是 bug。',
        '演算法摘要': 'def/use 抽取用 AST 分析，DU-pair 枚舉用 BFS/DFS，def-clear 路徑用可達性分析。',
        '小結': 'Data Flow Coverage 能捕捉 structure-only 準則漏掉的語意錯誤。掌握 def/use 對是後續所有資料流討論的基礎。',
        '課堂練習': '練習 1（手工找 def/use 對）是最核心的技能訓練。練習 3（比較 coverage 強度）適合作討論。',
        '進一步閱讀': 'A&O §15 有完整的資料流理論。工具實作在 src/utils/dataFlow.js。',
    },
    '05-logic-coverage': {
        'Logic Coverage': '本講是系列中最密集的理論講次，14 條準則需要一些時間消化。建議分兩堂課：第一堂講基礎準則，第二堂講 DNF/IC/UTP。',
        '從圖走進邏輯': '從 CFG 的分支條件出發：if (a && b) 有兩個子句（clauses），Logic Coverage 要求在子句層次測試。',
        '術語': '釐清 predicate / clause / binding 的層次：predicate 是整個布林表達式，clause 是不可再分的原子條件。',
        '真值表（Truth Table）': '真值表是 Logic Coverage 的計算基礎。工具裡的真值表是互動的——可以直接在欄位看到哪些列滿足各準則。',
        '預測子文法': '工具接受的語法是 JavaScript 的布林表達式，支援 &&、||、!、()、===、!== 等。',
        '14 條準則總表（語意系列）': '語意系列（PC/CC/CoC/GACC/CACC/RACC/GICC/RICC/IC）關注的是「子句如何影響 predicate 的值」。',
        '14 條準則總表（DNF / 語法系列）': 'DNF 系列（UTPC/MUTPC/NFPC/MNFPC）關注的是「DNF 項的覆蓋」，適合從代數角度思考。',
        'Subsumption（語意系列）': 'CACC 是語意系列中最常被實務採用的準則，因為它比 ACC 強但比 IC 弱，在測試成本和強度之間取得平衡。',
        '教科書範例：`(a && b) || c`': '這個三子句範例可以完整展示所有 14 條準則的差異。強調 CACC 的行對稱性是工具顏色高亮的設計依據。',
        '手算：PC / CC': 'PC 只需要 predicate 各真假一次；CC 要求每個子句各真假一次（不管其他子句）。',
        '手算：CACC（對 a 為主子句）': 'CACC 要求：固定其他子句的值，使 a 的真假能決定 predicate 的真假。這就是「deterministic」的意思。',
        'DNF 與 Quine–McCluskey': 'Quine–McCluskey 是最小化 DNF 的標準算法。工具用它計算 implicants，用於 UTPC/MUTPC 準則。',
        'IC、UTP、NFP': 'IC 是語意系列中最強的準則；UTPC 是 DNF 系列中最基本的。兩者在不同場景下各有優勢。',
        'CUTPNFP 直觀': 'CUTPNFP = UTPC ∩ NFP，是同時滿足 clause 覆蓋和 DNF 項覆蓋的複合準則。',
        'Karnaugh Map（n = 1–4）': 'K-map 是視覺化真值表的工具，特別適合展示哪些 minterm 被準則要求覆蓋。',
        'K-map cell 顯示元素': '工具的 K-map 用顏色區分：哪些 cell 被要求覆蓋（需求行）、哪些已被測試覆蓋。',
        '工具演示：選範例與輸入': '建議現場選 (a && b) || c，讓學生跟著操作，逐步切換準則觀察需求列表的變化。',
        '工具演示：真值表': '真值表每列都有對應的 DNF 分析和子句值。讓學生找出哪一列「只改變 a 的值就能決定 predicate」。',
        '工具演示：CACC criterion': 'CACC 每個子句需要兩列（主子句為 T 和 F，其他子句讓 predicate 可被主子句決定）。',
        '工具演示：IC + DNF + K-map': 'IC 通常需求列最多。K-map 會同步高亮被 IC 要求的 minterm cell。',
    },
    '06-program-mutation': {
        'Program Mutation': '本講換個視角：不測「程式」，而是測「測試集」有多強。Mutation score 是一個客觀的測試品質指標。',
        '換個視角：測「測試」': '傳統測試回答「程式對不對」，Mutation Testing 回答「我的測試好不好」。這是個元問題（meta-question）。',
        'Mutation Testing 三步驟': '三步驟：生成 mutants → 對每個 mutant 跑測試集 → 計算 mutation score。分子是 killed，分母是所有 mutants。',
        '為什麼是「killed」': 'killed 意味著測試集至少有一個測試能區分 mutant 和原始程式。這就是測試集「殺死」mutant 的意思。',
        '15 個 Operators（Procedural 11 個）': 'AOR（算術替換）和 ROR（關係替換）是最常見的 operator，也是最容易手算的。',
        '15 個 Operators（Object-Oriented 4 個）': 'OO operator 針對類別繼承和多型，在 Java/C++ 程式中特別重要。本工具目前實作 11 個 procedural operator。',
        '教科書範例：AOR on max(a, b)': '手算時，把 a + b 換成 a - b、a * b 等，問學生哪個 mutant 最容易被殺死。',
        '教科書範例：ROR on max(a, b)': 'a > b 換成 a >= b 是最微妙的 ROR mutant——只有在 a == b 時才有差異，測試集需要包含這個邊界情況。',
        'Equivalent Mutant：難解的部分': 'Equivalent mutant 是 mutation testing 最大的挑戰——無論如何跑測試，它都不會被殺死，因為它和原始程式語意上等價。',
        '工具：總覽': '工具左側是程式輸入和測試集，右側是 mutant 列表和 killed/alive 統計。建議讓學生先看 summary 數字。',
        '工具：執行流程': '點 "Run Mutation" 後工具會依序：解析程式 → 生成所有 mutant → 對每個 mutant 跑所有測試 → 計算 score。',
        '工具：mutants 列表': '每個 mutant 可以點開看 diff——哪一個 operator 在哪個 token 上做了什麼替換。',
        '工具：per-test 結果': '在 mutant 詳細頁可以看哪些測試殺死了它、哪些沒有。這幫助學生理解為什麼某個測試比另一個強。',
        'OO 演示：shapeHierarchy': 'shapeHierarchy 範例展示 OO mutation：把子類別實例替換、修改多型呼叫等。適合有物件導向背景的學生。',
        '持久化：test set 與 cloud sync': '工具支援雲端同步測試集，方便課堂上學生共用同一份 mutant 清單討論。',
        '演算法窺探：mutate pipeline': 'AST 轉換是生成 mutant 的核心技術。工具對每個 operator 都有對應的 AST visitor。',
        '常見陷阱': 'Coverage 高 ≠ Mutation score 高。可以舉例：coverage 100% 但測試只斷言不崩潰，mutation score 可能很低。',
        '小結': 'Mutation score 是測試集強度的客觀衡量指標。目標不是 100%（equivalent mutants 做不到），而是接近 80–90%。',
        '課堂練習': '練習 1（手算 AOR mutants）是最重要的基礎技能。練習 3（等價 mutant 判斷）適合進階學生。',
        '進一步閱讀': 'A&O §11.2 有完整的 mutation operator 定義。PIT 是業界最常用的 Java mutation testing 工具。',
    },
    '07-grammar-and-string-mutation': {
        'Grammar-Based Testing': '本講把「文法」當作測試的 subject，不是測試的工具。文法定義合法輸入的結構，覆蓋準則要求生成覆蓋文法的測試案例。',
        '為什麼是 Grammar-Based Testing': '任何接受結構化輸入的系統（parser、compiler、API）都可以用文法定義輸入空間，再用覆蓋準則設計測試。',
        '兩條教學主線': '本講同時涵蓋 Grammar Coverage（測覆蓋 BNF）和 String Mutation（突變字串找邊界）。兩條主線互補。',
        'BNF 速覽': 'BNF 的 `::=`、`|`、`*`、`+` 語法是文法測試的語言。工具接受標準 BNF 格式，自動推導。',
        '內建文法': '工具有三個內建文法（arithmetic、URL、JSON）。讓學生先試 arithmetic，觀察 derivation 樹狀展開。',
        'Derivation：BFS 左推導': 'BFS 左推導保證最短推導先出現。這讓工具能在合理時間內找到滿足覆蓋準則的最少測試集。',
        '兩條覆蓋指標': 'PDC（Production Coverage）要求每個產生式至少用一次；TSC（Terminal Symbol Coverage）要求每個終端符號至少出現一次。',
        '工具：總覽': '左側輸入文法，右側看 derivation 列表和覆蓋統計。讓學生先試預設文法，再換成自己寫的文法。',
        '工具：derivations + PDC / TSC': '工具同步高亮哪些產生式被覆蓋（PDC）和哪些終端符號被覆蓋（TSC）。',
        'Grammar Mutation：4 個 operators': 'operator 針對文法本身：替換、刪除、插入非終端、修改量詞。這些 mutant 模擬「文法錯誤」。',
        'Kill criterion（Grammar Mutation）': '如果測試案例能接受 original grammar 生成的字串但拒絕 mutant grammar 生成的字串（或反之），則 mutant 被殺死。',
        '工具：grammar mutants': '工具列出所有 grammar mutant 和它們的 kill 狀態。可以問學生：哪種 operator 的 mutant 最難被殺死？',
        '接到 Strings：Mutation on Strings': 'String Mutation 是字串層次的突變測試，不修改文法，而是修改單個字串輸入，尋找邊界情況。',
        '5 個 String Mutation Operators': 'AOR/LCR/SOR/UOI/COR 在字串層次有對應版本：插入、刪除、替換字元等。',
        '為什麼分 positive / negative': 'positive test 應該通過（文法正確的輸入），negative test 應該失敗（故意錯誤的輸入）。兩種都要設計。',
        '工具：string mutation': '工具的 string mutant 列表同時顯示 positive/negative 分類，方便學生確認每個 mutant 的預期行為。',
        '演算法窺探': 'BFS 推導用遞迴展開 + 去重複。Grammar mutation 是對 AST（文法樹）做 operator 替換。',
        '從雲端載入 grammar': '雲端載入功能讓學生可以共享自定義文法。適合分組作業：每組設計一個文法，互相測試。',
        '小結': '文法既是測試輸入的規格，也可以是測試的 subject。PDC/TSC 幫助確保文法的所有「路徑」都被測試。',
        '課堂練習': '練習 1（手工推導）是最基本的技能。練習 3（JSON 文法覆蓋）適合作進階作業。',
    },
    '08-spec-mutation': {
        'Specification Mutation': '本講是突變系列的終點站：把突變的對象從程式碼換成規格（predicate）和狀態機（FSM）。',
        '三講對照': '第 6 講突變「程式」，第 7 講突變「文法」，本講突變「規格（predicate）」和「狀態機（FSM）」。',
        'Specification Mutation 是什麼': 'Specification mutant 是對 predicate 做算子替換，測試集需要能區分原始規格和每個 mutant。',
        '6 個 Operators': 'AOR/ROR/LCR/MOR/AOD/COD 是 specification mutation 的六個 operator。LCR（&&↔||）和 ROR（>↔>=）是最常見的。',
        '範例分類：basic vs SMV': 'basic operator 直接替換算子；SMV（Safety Monitor Violation）operator 則針對安全監控模式設計。',
        'SMV 範例對照表': 'SMV 在形式驗證（formal verification）場景中特別重要，例如航空、汽車電子的安全規格。',
        '範例：`(a || b) && c` 對 6 個 operator': '讓學生手算每個 operator 對這個 predicate 的效果，再比對工具的 mutant 列表。',
        'Kill 演算法': 'kill 的條件：原始 predicate 和 mutant predicate 在某個輸入下輸出不同。測試集需要包含這樣的輸入。',
        'Safety Monitor FSM': 'FSM（有限狀態機）是規格的另一種形式。工具同時展示 original FSM 和 mutant FSM 的並列對比。',
        '為什麼是 memoryless': '大多數 FSM 是無記憶的（memoryless）：下一狀態只取決於當前狀態和輸入，不記得歷史。',
        'diff = killer set': '兩個 FSM 的差異集（diff）就是能殺死 FSM mutant 的測試集。工具直接計算並顯示這個差異。',
        '工具：總覽': '工具分三區：左側是 predicate 輸入，中間是 mutant 列表，右側是 FSM 並列視圖。',
        '工具：mutants 與 score': '工具同時顯示 predicate mutant 和 FSM mutant 的 kill 狀態，以及整體 mutation score。',
        '工具：雙 FSM 並列': '並列視圖讓學生直接看出 original 和 mutant FSM 的差異在哪個狀態轉換。',
        '工具：SMV 原始碼': '工具展示 SMV 格式的規格，讓學生理解形式驗證工具（如 NuSMV）如何解讀這些規格。',
        '持久化': '工具儲存最近的 predicate 和 FSM，方便跨 session 繼續工作。',
        '演算法總覽': 'predicate mutation 用 AST 替換算子；FSM mutation 用狀態轉換表的增刪改；diff 計算用 BFS。',
        '與其他章節的關聯': 'Specification Mutation 連接形式驗證（§16）和 Logic Coverage（§4–5）。這是課程中「最理論」的一講。',
        '小結': 'Specification Mutation 讓我們測試「規格本身」是否足夠精確。一個好的測試集應該能殺死所有非等價的規格 mutant。',
        '課堂練習': '練習 1（手算 LCR mutant）最基本。練習 3（FSM diff）適合有自動機基礎的學生。',
    },
    '09-fuzz-testing': {
        'Fuzz Testing': '從本講開始，系列進入「自動化測試生成」三連講（Fuzz → Symbex → Concolic）。Fuzz 是最簡單但仍非常有效的方法。',
        '觀念定位': 'Fuzz testing 的核心優勢：完全自動化、無需規格、能找到人工測試難以發現的邊界情況。缺點：覆蓋率不可預期。',
        '何時用 fuzz': '最適合：接受大量外部輸入的系統（parser、網路協議、檔案處理）。不適合：需要特定語意輸入才能觸發的 bug。',
        'Fuzz 三步驟': '本工具實現：生成隨機整數/布林輸入 → 執行被測函式 → 記錄崩潰和分支 trace。',
        '技術核心：分支 instrumentation': '工具在執行前「插樁」（instrument）每個 if/while 條件，把 taken/not-taken 記錄到 branch trace 陣列。',
        '從 trace 到 CFG 覆蓋': 'Branch trace 對應到 CFG 的 edge，工具計算 node coverage 和 edge coverage 百分比。',
        '內建 6 個範例': '六個範例覆蓋：簡單算術、邊界判斷、遞迴（fibonacci）、字串處理、迴圈、多分支。',
        '工具：總覽': '左側輸入程式碼和測試數量，右側是測試案例列表（pass/crash）和 CFG 視圖。',
        '工具：testCases 與 CFG': '點擊測試案例，CFG 會高亮該次執行所走過的 node 和 edge。讓學生找出「哪個分支從未被覆蓋」。',
        '工具：crash 偵測': 'Crash = 執行時拋出 exception。工具顯示崩潰率和錯誤訊息，幫助定位問題。',
        '隨機輸入策略': '本工具的第一階段（Phase 1）用純隨機整數/布林；第二階段（Phase 2）對有趣的種子做變異（±1、邊界值、bitflip）。',
        'Fuzz 的本質限制': '純隨機 fuzz 無法處理「magic number」（例如需要輸入特定常數才能觸發的分支）。Concolic 執行（#11）解決這個問題。',
        '常見陷阱': '高 node coverage 不代表測試好：如果斷言只有「不崩潰」，fuzz 找不到邏輯錯誤。',
        '演算法窺探': '插樁用正則表達式替換 if/while 條件。迴圈有迭代次數上限（10000 次）防止無窮迴圈。',
        '小結': 'Fuzz 是「以量取勝」的策略。第二階段的 mutation（变異）讓工具能探索隨機輸入遺漏的邊界。',
        '課堂練習': '練習 1（觀察崩潰率）最直觀。練習 3（比較 fuzz 和 random 的差異）適合作討論主題。',
        '進一步閱讀': 'AFL 和 libFuzzer 是業界最廣泛使用的 fuzz 工具。學生有興趣可以試著對自己的程式跑一次真正的 AFL。',
    },
    '10-symbolic-execution': {
        'Symbolic Execution': 'Symbolic execution 是本系列最「數學」的方法：把程式輸入當作符號，用約束求解器找到覆蓋每條路徑的具體輸入。',
        '從 fuzz 走到 symbex': 'Fuzz 是「盲目嘗試」，symbex 是「有系統地分析」。Symbex 能保證找到每條可達路徑的輸入（如果可解）。',
        '三件事：env / pc / branches': '執行狀態 = 環境（變數符號值）+ 路徑條件（走到這裡的約束）+ 分支 trace（走過哪些分支）。',
        'fork 機制': '每遇到一個條件分支，symbex 「分叉」成兩個執行狀態（true 和 false 兩條路）。這就是路徑爆炸的根源。',
        '找 witness：bounded brute-force': '工具用有界的暴力搜尋（[-10, 10] 整數格點）找滿足路徑條件的具體值。真實 symbex 用 SMT solver（如 Z3）。',
        '為什麼 infeasible path 重要': '如果一條路徑的約束不可滿足（infeasible），就代表不存在測試案例能走這條路——這本身就是重要的測試資訊。',
        '內建 4 個範例': '四個範例覆蓋：簡單條件、多分支、巢狀條件、帶等式約束的路徑。',
        '工具：總覽': '左側輸入程式碼，右側是路徑列表（每條路徑有路徑條件、witness、是否 infeasible）。',
        '工具：路徑列表': '每個路徑項顯示：路徑條件（數學式）、具體 witness（x=1, y=-3）、執行結果。點擊路徑高亮 CFG。',
        '工具：CFG 路徑高亮': '點擊路徑項，CFG 會用紫色高亮對應的 node 和 edge 序列。讓學生確認路徑條件和 CFG 路徑一致。',
        'Path explosion': '指數級的路徑數是 symbex 最大的挑戰。工具用深度限制（max paths）避免爆炸，但真實系統需要更複雜的策略。',
        '演算法窺探': '工具用遞迴 DFS 展開 AST，在每個條件分支點克隆執行狀態，累積路徑條件，最後求解。',
        '真實 symbex 系統的差異': '真實系統（KLEE、Angr、S2E）用 Z3/Boolector 等 SMT solver，能處理整數、字元、指標等複雜約束。',
        '小結': 'Symbex 系統地覆蓋所有可達路徑，但受制於路徑爆炸。Concolic（#11）是在 fuzz 基礎上加入 symbex 的混合策略。',
        '課堂練習': '練習 1（手動追蹤路徑條件）最重要。練習 3（infeasible 路徑）適合有代數基礎的學生。',
        '進一步閱讀': 'KLEE 是最著名的 symbex 工具。EXE 是 KLEE 的前身，A&O §13 有詳細介紹。',
    },
    '11-concolic-execution': {
        'Concolic Execution': 'Concolic = concrete + symbolic。核心想法：用具體值執行，同時追蹤符號路徑條件，再翻轉條件找新路徑。',
        '三講對照：fuzz → symbex → concolic': 'Fuzz 最快但盲目；Symbex 系統但慢；Concolic 折衷：從具體執行開始，用 symbex 引導下一個輸入。',
        '名字由來': 'Concolic = concurrent symbolic + concrete。DART（2005）是最早提出這個名詞的論文，值得一提。',
        '核心 4 步驟（每次迭代）': '每次迭代：執行 → 收集路徑條件 → 翻轉最後未探索的分支 → 求解新輸入。這四步驟是整個算法的心臟。',
        '「翻轉最後未探索分支」': '「翻轉」的意思是：把路徑條件的最後一個約束取反（negation），然後求解。這保證下一次走不同的分支。',
        '與 symbex 的關鍵差異': 'Symbex 同時追蹤所有路徑（指數級空間）；Concolic 一次走一條路徑（線性空間），逐步探索。',
        '內建 4 個範例': '四個範例和 symbex 相同，方便學生對比兩種方法找到 witness 的過程有何不同。',
        '工具：總覽 + 設定': '工具的「Seed Input」讓學生控制起點；「Max Iterations」控制探索深度。建議先用小迭代數觀察行為。',
        '工具：迭代列表': '每個迭代項顯示：具體輸入、路徑條件、執行結果、哪個分支被翻轉。',
        '工具：CFG 同步高亮': '工具在點擊迭代項時，CFG 同步高亮該次迭代走過的路徑，讓學生追蹤探索的進程。',
        '演算法窺探': '工具用 AST 解釋器同時維護具體值（concrete）和符號表達式（symbolic），在分支點記錄兩者。',
        '路徑收斂': 'Concolic 不保證找到所有路徑（受限於迭代數），但能用有限步驟探索大量路徑，比純 fuzz 更有系統。',
        '真實系統與本工具': '真實系統（SAGE、DrChecker）用 Z3 求解約束，能處理字元、記憶體位址等複雜類型。本工具用整數暴力搜尋簡化示範。',
        '小結': 'Concolic 是 fuzz + symbex 的最佳折衷：從具體執行出發，用符號分析引導下一步，避免路徑爆炸。',
        '課堂練習': '練習 1（追蹤迭代）是最核心的理解練習。練習 3（比較與 fuzz 的差異）適合最後的討論。',
        '進一步閱讀': 'DART 論文（Godefroid 等，2005）是 concolic 的開山之作。SAGE 是 Microsoft 用於 Windows fuzzing 的 concolic 工具。',
    },
    '12-test-generation': {
        'Test Generation from Coverage': '本講把前面所有準則串起來：用覆蓋準則生成「最少的測試集」覆蓋「所有需求」。這是整個系列的綜合應用。',
        '本講在系列中的位置': '前面各講「定義準則」，本講「自動化生成滿足準則的測試集」。這是從理論到工程實踐的最後一哩路。',
        '問題定義': '問題：給定一個函式和一個覆蓋準則，找出最少的測試案例集合，使得所有準則要求的 requirement 都被覆蓋。',
        '計算流水線': '流水線：程式碼 → CFG → 覆蓋需求 → Greedy Set Cover → 最少測試集 → 執行驗證。',
        '關鍵模組': '四個模組各司其職：pathFinder（路徑搜尋）、TestPathSelector（貪婪選取）、TestCaseBuilder（具體化）、Runner（執行驗證）。',
        'Greedy Set Cover': 'Greedy Set Cover 是 NP-hard 問題的近似算法：每次選覆蓋最多未覆蓋 requirement 的路徑。近似比 ln(n)，通常實際效果很好。',
        '8 個 Coverage 準則': '工具支援 NC/EC/ECC/PPC/ADUP/ADU/ADef + CACC。可以讓學生選不同準則，觀察測試集大小的差異。',
        '工具：總覽': '左側輸入程式碼，右側分三區：requirements 列表、selected tests 列表、CFG 視圖。',
        '工具：Requirements 卡': 'Requirements 卡列出所有覆蓋需求（node/edge/path/clause）。點擊需求高亮 CFG，並顯示哪個測試覆蓋它。',
        '工具：Minimal Tests 卡': 'Minimal Tests 卡列出 Greedy Set Cover 選出的最少測試集。每個測試顯示它覆蓋了哪些 requirement。',
        '工具：CFG 互動': '點擊 requirement 或 test，CFG 同步高亮相關的 node/edge/path。幫助學生建立準則和程式結構的視覺連結。',
        '範例：abs(x) + Edge Coverage': 'abs(x) 是最簡單的示範：只有兩條 edge，需要兩個測試（x>0 和 x<=0）。',
        '範例：triangle + Prime Path Coverage': 'Triangle 有多條 prime path，需要的測試集明顯比 edge coverage 大。這展示了準則強度的影響。',
        'Infeasible Requirements': '有些需求對應的路徑在程式語意上不可達（infeasible）。工具用紅色標示這些需求，並跳過它們。',
        '與 #10/#11 的差異': 'Symbex/Concolic 用約束求解找輸入；本工具用 brute-force 整數格點搜尋。前者更強大，後者更直觀易解釋。',
        '程式設計重點': '工具的核心挑戰：如何把 coverage requirement（抽象路徑）轉化為具體的輸入值（整數組合）。',
        '小結': '本講把前面的「定義準則」轉化為「自動化生成」。目標是讓學生理解：覆蓋準則不只是評量指標，也是生成測試的規格。',
        '課堂練習': '練習 1（觀察不同準則的測試集大小）最直觀。練習 3（修改程式觀察 CFG 和需求的變化）適合作互動演示。',
        '進一步閱讀': 'A&O §8 有 Test Path 的完整理論。工具的 Set Cover 實作在 src/utils/setCover.js。',
    },
    '13-logic-binding': {
        'Logic Coverage Binding': '本講解決 Logic Coverage 的「最後一哩」問題：把抽象的子句（a、b、c）對應到具體的程式表達式，才能實際執行測試。',
        '問題：Logic Coverage 的「落地鴻溝」': '學生可以計算 CACC 的需求表，但不知道如何生成滿足「a=T, b=F」的具體輸入。Binding 就是填補這個鴻溝的機制。',
        '核心概念：三層對應': '三層：準則（CACC）→ 子句真值組合（a=T, b=F）→ 具體 witness（x=1, y=10）。Binding 負責第二到第三層的轉換。',
        'Binding 介面': '工具的 Binding 面板緊接在邏輯覆蓋工具之下。選好準則後，每個需求行都有對應的 witness 顯示。',
        'Clause Binding 子面板構成': '每個子句（a, b, c）對應一個輸入框，讓學生填入 JavaScript 表達式（例如 x > 0）。',
        '結果表格四欄': '四欄：行號（哪個需求）、子句真值組合（a=T, b=F, c=T）、約束式（(x > 0) && !(y < 10)）、witness（x=1, y=10）。',
        '求解演算法：bounded brute-force': '工具先嘗試解析型解法（interval arithmetic），若失敗則用暴力搜尋 [-10, 10] 整數格點的 Cartesian product。',
        '為什麼選「最小絕對值」順序': '從 0 開始、依 |x| 遞增搜尋，確保找到最接近 0 的 witness，讓學生驗算時最容易手工計算。',
        '範例程式：abs(x)': 'abs(x) 的 predicate 是 x >= 0，只有一個子句。Binding 非常直接：a=T → x=0，a=F → x=-1。',
        '範例程式：max(a, b)': 'max(a, b) 的 predicate 是 a >= b，一個子句。CACC 需要 a=T 和 a=F 兩個 witness。',
        '範例程式：triangle': 'triangle 有多個子句，CACC 需求較多。讓學生逐行驗算每個 witness 是否真的滿足對應的子句真值組合。',
        '自動填入（Auto-fill）': 'Auto-fill 讀取所選範例的 defaultBindings，一鍵填入所有子句表達式。讓學生用 auto-fill 快速看到結果，再手動修改學習。',
        'Binding 工具演示': '現場選 triangle → 選 CACC → 點 auto-fill。讓學生觀察 witness 表格，找出哪一行對應教科書的哪個需求。',
        '搜尋範圍設定': '搜尋範圍預設 [-10, 10]。如果子句表達式涉及大數（例如 x > 50），可以擴大範圍找到 x=51 等 witness。',
        '限制與後續': '限制：工具只能處理整數 witness，且搜尋範圍有限。解析型解法（interval arithmetic）已在 B1 版本加入，可處理 x > 50 等情況。',
        '小結': 'Binding 把 Logic Coverage 從「紙上作業」變成「可驗證的測試輸入」。掌握這個三層對應，才算真正學會 Logic Coverage 的工程應用。',
        '課堂練習': '練習 1（手填 binding 驗算 witness）最重要。練習 3（擴大搜尋範圍）適合理解 solver 限制。',
        '進一步閱讀': 'A&O §4–5 有 Logic Coverage 的完整理論。Binding 的 solver 實作在 src/utils/logicBinding.js。',
    },
}

EN = {
    '01-course-intro': {
        'Software Testing Visualized': 'Welcome students. This series has 13 lectures, each paired with a browser-based interactive tool designed to turn abstract test criteria into measurable engineering practice.',
        'Course Goals': 'Emphasize "hands-on": every requirement is a clickable item in the tool and students see coverage metrics update in real time, rather than just memorizing definitions.',
        'Course Map': 'The course has expanded to 13 lectures (adding Data Flow #4 and Logic Binding #13). Three main threads: graph (#3–#4), logic (#5, #13), and mutation (#6–#8).',
        'Learning Dependencies': 'The three threads can be taken in any order, but Graph Coverage is a prerequisite for Data Flow. Ask: which thread are you currently on?',
        'Three Categories': '"Code visibility" is the core classification axis. Ask students which category their daily testing falls into — the answer is usually gray-box, which prompts a useful discussion.',
        'Black-Box': 'BVA is the most commonly underestimated but highly effective technique. Emphasize: all four black-box techniques need no source code and can be designed at the requirements review stage.',
        'White-Box': 'Core idea for white-box: "structure defines criterion." Each subsequent lecture dives into one structure (graph, logic, mutation) as a concrete realization of this principle.',
        'Gray-Box': 'Ask: has anyone ever seen all their dependencies\' source code? This question usually makes everyone realize that almost all real-world testing is gray-box.',
        'Tool: Testing Method Tree': 'Open the tool live. Click toggle-all-btn to expand all 16 techniques, then ask students to find the visibility-fill bar and state that black-box is 0%.',
        'Tool: White-Box Expanded': 'Point out symbex and concolic — high-end techniques used in industry for automated test generation. Covered in depth in lectures #10–#11.',
        'Three Mental Models': 'These three mental models (abstract, cover, mutate) are the skeleton of the entire series. Every criterion fits into one of them — a useful framework for organizing knowledge.',
        'Summary': 'This lecture is an overview — no need to memorize everything. The point is awareness of the landscape; each subsequent lecture will go deep into one criterion.',
        'Classroom Exercise': 'Reserve 10–15 minutes for hands-on tool exploration. Exercise 1 is the most essential; exercises 3–4 make good take-home discussion topics.',
        'Further Reading': 'Students wanting depth can read A&O §1–2. The full tool specification is in docs/Specification.zh-TW.md, covering design decisions for all components.',
    },
    '02-testing-flow-pyramid': {
        'Testing Flow': 'This lecture connects two complementary views: the testing flow tells you "what to do when," and the pyramid tells you "the right proportion for each layer."',
        'Two Main Threads': 'Both views are needed. Flow gives the engineering lifecycle; pyramid gives the resource allocation ratio. Neither alone is sufficient.',
        'Testing Flow: Six Steps': 'The key word is "repeatable": every time code changes, you run the flow again — not just before a release.',
        'Tool: Auto-Play Flow': 'Open the tool and click auto-play to cycle through the six steps. Ask students to find the step they most commonly skip in their own projects.',
        'Why This Flow Still Matters': 'Even with CI/CD, this six-step logic still holds. CI/CD automates the flow; it does not eliminate it.',
        'The Test Pyramid View': 'The pyramid\'s most important insight: unit tests should be most numerous, E2E tests fewest, because of the speed and cost difference.',
        'Four Layers': 'Ask students: what does your project\'s pyramid look like? Is it an inverted triangle (lots of E2E, few unit tests)?',
        'Tool: Pyramid + Cards': 'The pyramid in the tool is interactive — clicking each layer expands a detail card. Ask students to click and read the examples for each layer.',
        'Test Pyramid Principle': 'Mike Cohn\'s pyramid principle is widely cited, but many teams invert it. Ask why E2E tests shouldn\'t be the backbone of the test suite.',
        'Two Anti-Pyramid Traps': 'The ice-cream cone and hourglass are common anti-patterns. Ask students which shape their project is, and discuss how to improve it.',
        'Connecting Both Views': 'Key connection: "Test Design" in the six steps corresponds to the pyramid layer decision — choose the layer first, then design the test cases.',
        'Summary': 'The core message: flow makes testing orderly, pyramid makes resource allocation rational. Both are essential.',
        'Classroom Exercise': 'Exercise 1 (draw your own pyramid) is the most important. Exercise 3 (CI/CD discussion) guides students to think about the limits of automation.',
        'Further Reading': 'Fowler\'s blog post "TestPyramid" is the best secondary resource for this concept — short and precise.',
    },
    '03-graph-coverage': {
        'Graph Coverage': 'This lecture is the graph-theoretic foundation of the entire series. Mastering CFG and coverage criteria here makes Data Flow (#4) and Test Generation (#12) flow naturally.',
        'Why Graph Coverage': 'CFG bridges program structure and measurable coverage criteria. Emphasize: not just if/while — any "flow" structure can be turned into a graph.',
        'What Is a CFG': 'Node = basic block, Edge = control flow transfer. Whiteboard a simple if-else CFG and have students fill in the nodes collaboratively.',
        'Five Structural Coverage Criteria': 'These five criteria form a strict subsumption hierarchy. Prime Path Coverage is the "king" — it subsumes most criteria below it.',
        'Subsumption': 'The subsumption diagram is the key tool for understanding criterion strength. Ask: why does Edge Coverage not subsume Prime Path Coverage?',
        'Textbook Example: Sample CFG': 'This sample CFG is the standard example from Ammann & Offutt. Have students compute NC by hand first, then check against the tool.',
        'By Hand: Node Coverage': 'NC requires each node to be visited at least once. Have students find the minimum number of test paths.',
        'By Hand: Edge Coverage': 'EC requires each edge to be covered at least once. Usually just one or two more paths than NC.',
        'By Hand: Prime Path Coverage': 'PPC requires covering all prime paths (longest simple paths). Emphasize this may be fewer than total paths — not every path needs to be covered.',
        'Tool Demo: Select Criterion': 'Open the tool live, select Node Coverage, and let it compute the requirement list. Observe how requirement count grows as criterion strength increases.',
        'Tool Demo: Metrics and Greedy Set Cover': 'The tool uses greedy set cover to find the minimum test set. Ask: does the greedy solution guarantee optimality? (No, but it\'s usually very close.)',
        'Tool Demo: Upload Code': 'Let students upload a simple function they wrote and watch the tool auto-generate a CFG. Note: the tool only handles JavaScript function syntax.',
        'Live Edit CFG': 'Live edit mode lets students directly modify the dot-format CFG, useful for manually constructing textbook examples.',
        'Summary': 'CFG + five criteria are the graph-theoretic backbone of this series. Mastering this makes Data Flow (#4) and Test Generation (#12) follow naturally.',
        'Classroom Exercise': 'Exercise 1 (compute prime paths by hand) is the most important foundational skill. Exercise 3 (upload your own code) works well as homework.',
        'Further Reading': 'A&O §3 has the complete CFG theory. The prime path algorithm in the tool is in src/utils/graphCoverage.js.',
    },
    '04-data-flow-coverage': {
        'Data Flow Coverage': 'This lecture extends CFG to "data flow," moving from structure to semantics. Defining def/use pairs is the core skill of this lecture.',
        'From Structure to Data': 'CFG only tracks "which edges are taken"; DFC also tracks "where variables are assigned and where they are used" — enabling detection of semantic errors.',
        'Three Core Concepts': 'The def-clear path is the most important concept: a def-use pair is valid only if the variable is not redefined between the def and the use.',
        'Three Data Flow Criteria': 'All-Defs < All-Uses < All-DU-Paths in strength. All-Uses is the most commonly adopted criterion in practice.',
        'Subsumption (Structure + Data Flow)': 'Data flow and structural coverage criteria interleave in subsumption. All-Uses subsumes Edge Coverage — important but non-obvious.',
        'Textbook Example: Triangle Problem': 'The Triangle Problem is the standard A&O example. Have students manually find all def/use pairs, then compare with the tool.',
        'def/use Extraction Rules': 'Assignment statements and function parameters are the most common def points; conditional tests and operands are the most common use points.',
        'Tool Demo: DFG View': 'The DFG view expands each CFG node into def points and use points. Let students trace the arrows connecting defs to uses.',
        'Tool Demo: All-Defs': 'All-Defs only requires each def to reach at least one use. This is the weakest data flow criterion and usually has the fewest requirements.',
        'Tool Demo: All-Uses': 'All-Uses requires covering every def-use pair. Ask: if a def has 5 uses, how many test paths are needed?',
        'Tool Demo: All-DU-Paths': 'All-DU-Paths is the strongest data flow criterion, requiring coverage of every def-clear path for every def-use pair. Test sets are usually large.',
        'Why DFG Can Be Empty': 'If a function has no variable assignments (only a return statement), the DFG will be empty. This is a design choice, not a bug.',
        'Algorithm Summary': 'def/use extraction uses AST analysis; DU-pair enumeration uses BFS/DFS; def-clear paths use reachability analysis.',
        'Summary': 'Data Flow Coverage catches semantic errors missed by structure-only criteria. Mastering def/use pairs is foundational for all subsequent data flow discussions.',
        'Classroom Exercise': 'Exercise 1 (manually find def/use pairs) is the most critical skill-building exercise. Exercise 3 (compare coverage strengths) works well as a group discussion.',
        'Further Reading': 'A&O §15 has the complete data flow theory. The tool implementation is in src/utils/dataFlow.js.',
    },
    '05-logic-coverage': {
        'Logic Coverage': 'This is the most theory-dense lecture in the series. 14 criteria take time to absorb. Suggested split: first session covers basic criteria, second covers DNF/IC/UTP.',
        'From Graph to Logic': 'Starting from CFG branch conditions: if (a && b) has two clauses. Logic Coverage requires testing at the clause level, not just the branch level.',
        'Terminology': 'Clarify the predicate/clause/binding hierarchy: predicate is the whole boolean expression; clause is an atomic (indivisible) sub-condition.',
        'Truth Table': 'The truth table is the computational foundation of Logic Coverage. The tool\'s truth table is interactive — students can see which rows satisfy each criterion.',
        'Predicate Grammar': 'The tool accepts JavaScript boolean expressions: &&, ||, !, (), ===, !==, and comparisons.',
        'Semantic Criteria (14 Total)': 'The semantic series (PC/CC/CoC/GACC/CACC/RACC/GICC/RICC/IC) focuses on "how clauses determine predicate value."',
        'DNF / Syntactic Criteria': 'The DNF series (UTPC/MUTPC/NFPC/MNFPC) focuses on "coverage of DNF implicants" — an algebraic perspective.',
        'Subsumption (Semantic)': 'CACC is the most practically adopted criterion: stronger than ACC, weaker than IC, balancing test cost and strength.',
        'Textbook Example: (a && b) || c': 'This three-clause example can fully illustrate all 14 criteria. The paired row structure in CACC is the basis for the tool\'s color highlighting design.',
        'By Hand: PC / CC': 'PC requires predicate true and false at least once each; CC requires each clause true and false (regardless of other clauses).',
        'By Hand: CACC (a as major clause)': 'CACC requires: fixing other clauses\' values such that a\'s truth determines the predicate\'s truth — this is what "deterministic" means.',
        'DNF and Quine-McCluskey': 'Quine-McCluskey is the standard DNF minimization algorithm. The tool uses it to compute implicants for UTPC/MUTPC criteria.',
        'IC, UTP, NFP': 'IC is the strongest semantic criterion; UTPC is the most basic DNF criterion. Each has advantages in different scenarios.',
        'CUTPNFP Intuition': 'CUTPNFP = UTPC ∩ NFP — a composite criterion satisfying both clause coverage and DNF implicant coverage simultaneously.',
        'Karnaugh Map': 'K-maps visually represent truth tables, especially useful for showing which minterms are required by each criterion.',
        'K-map Cell Elements': 'The tool\'s K-map uses colors to distinguish: cells required by the criterion (requirement rows) vs. cells already covered by tests.',
        'Tool Demo: Select Example': 'Select (a && b) || c live, have students follow along switching criteria and observing how the requirement list changes.',
        'Tool Demo: Truth Table': 'Each truth table row has corresponding DNF analysis and clause values. Have students find which row can "determine the predicate solely by changing a."',
        'Tool Demo: CACC Criterion': 'CACC needs two rows per clause (major clause T and F, other clauses set to make predicate determinable by major clause).',
        'Tool Demo: IC + DNF + K-map': 'IC usually has the most requirements. The K-map synchronously highlights the minterms required by IC.',
    },
    '06-program-mutation': {
        'Program Mutation': 'This lecture shifts perspective: instead of testing the program, we test the test suite itself. Mutation score is an objective metric for test suite quality.',
        'A Different Perspective': 'Traditional testing answers "is the program correct?"; mutation testing answers "how strong is my test suite?" — a meta-question.',
        'Three Steps of Mutation Testing': 'Three steps: generate mutants → run test suite against each mutant → compute mutation score. Numerator = killed; denominator = all non-equivalent mutants.',
        'Why "Killed"': '"Killed" means the test suite has at least one test that can distinguish the mutant from the original program — the test "kills" the mutant.',
        '15 Operators (Procedural, 11)': 'AOR (arithmetic operator replacement) and ROR (relational operator replacement) are the most common operators and easiest to compute by hand.',
        '15 Operators (OO, 4)': 'OO operators target class inheritance and polymorphism, especially important in Java/C++ programs. The current tool implements 11 procedural operators.',
        'Textbook Example: AOR on max(a, b)': 'For hand calculation: replace a > b with a + b, a - b, a * b, etc. Ask which mutant is easiest to kill.',
        'Textbook Example: ROR on max(a, b)': 'a > b changed to a >= b is the most subtle ROR mutant — it differs only when a == b, so tests need to include this boundary case.',
        'Equivalent Mutant': 'Equivalent mutants are mutation testing\'s biggest challenge — no test can kill them because they are semantically identical to the original program.',
        'Tool: Overview': 'Left side: program input and test suite. Right side: mutant list and killed/alive statistics. Suggest students look at the summary numbers first.',
        'Tool: Execution Flow': 'Clicking "Run Mutation" triggers: parse program → generate all mutants → run all tests against each mutant → compute score.',
        'Tool: Mutant List': 'Each mutant can be expanded to see the diff — which operator applied to which token made what replacement.',
        'Tool: Per-Test Results': 'The mutant detail page shows which tests killed it and which didn\'t. This helps students understand why one test is stronger than another.',
        'OO Demo: shapeHierarchy': 'The shapeHierarchy example shows OO mutation: replacing subclass instances, modifying polymorphic calls, etc. Good for students with OO background.',
        'Persistence: Test Set & Cloud Sync': 'The tool supports cloud sync of test sets, making it easy for students to share the same mutant list for group discussion.',
        'Algorithm: Mutate Pipeline': 'AST transformation is the core technique for generating mutants. The tool has a corresponding AST visitor for each operator.',
        'Common Pitfalls': 'High coverage ≠ high mutation score. Example: 100% coverage but tests only assert "no crash" → mutation score can be very low.',
        'Summary': 'Mutation score is an objective measure of test suite strength. The goal is not 100% (impossible with equivalent mutants) but approaching 80–90%.',
        'Classroom Exercise': 'Exercise 1 (compute AOR mutants by hand) is the most important foundational skill. Exercise 3 (equivalent mutant judgment) works for advanced students.',
        'Further Reading': 'A&O §11.2 has complete mutation operator definitions. PIT is the most widely used Java mutation testing tool in industry.',
    },
    '07-grammar-and-string-mutation': {
        'Grammar-Based Testing': 'This lecture treats grammar as the test subject, not the test tool. Grammar defines the structure of valid inputs; coverage criteria require generating tests that cover the grammar.',
        'Why Grammar-Based Testing': 'Any system accepting structured input (parser, compiler, API) can use a grammar to define the input space, then apply coverage criteria to design tests.',
        'Two Educational Threads': 'This lecture covers Grammar Coverage (covering BNF productions) and String Mutation (mutating individual strings to find boundaries) — complementary approaches.',
        'BNF Overview': 'BNF\'s ::=, |, *, + syntax is the language of grammar testing. The tool accepts standard BNF format and automatically derives strings.',
        'Built-in Grammars': 'Three built-in grammars: arithmetic, URL, JSON. Start with arithmetic — observe how the derivation tree expands.',
        'Derivation: BFS Left Derivation': 'BFS left derivation ensures shortest derivations appear first, allowing the tool to find the minimum test set satisfying coverage criteria in reasonable time.',
        'Two Coverage Metrics': 'PDC (Production Coverage): each production used at least once; TSC (Terminal Symbol Coverage): each terminal appears at least once.',
        'Tool: Overview': 'Input grammar on the left, see derivation list and coverage statistics on the right. Start with the default grammar, then switch to a custom one.',
        'Tool: Derivations + PDC / TSC': 'The tool synchronously highlights which productions are covered (PDC) and which terminals are covered (TSC).',
        'Grammar Mutation: 4 Operators': 'Operators target the grammar itself: substitute, delete, insert non-terminal, modify quantifier. These mutants simulate "grammar errors."',
        'Kill Criterion (Grammar Mutation)': 'A test kills a grammar mutant if it accepts strings generated by the original grammar but rejects strings from the mutant grammar (or vice versa).',
        'Tool: Grammar Mutants': 'The tool lists all grammar mutants and their kill status. Ask: which operator type produces the hardest-to-kill mutants?',
        'String Mutation': 'String Mutation is character-level mutation testing — not modifying the grammar, but mutating individual string inputs to find boundary cases.',
        'Five String Operators': 'AOR/LCR/SOR/UOI/COR have character-level counterparts: insert, delete, substitute characters, etc.',
        'Positive vs. Negative': 'Positive tests should pass (grammatically correct input); negative tests should fail (deliberately incorrect input). Both must be designed.',
        'Tool: String Mutation': 'The string mutant list shows positive/negative classification, helping students verify the expected behavior of each mutant.',
        'Algorithm': 'BFS derivation uses recursive expansion + deduplication. Grammar mutation applies operator substitution to the grammar\'s AST.',
        'Load Grammar from Cloud': 'Cloud loading lets students share custom grammars. Good for group work: each group designs a grammar, then tests each other\'s.',
        'Summary': 'Grammar is both the specification of test inputs and can itself be the test subject. PDC/TSC help ensure all "paths" through the grammar are tested.',
        'Classroom Exercise': 'Exercise 1 (manual derivation) is the most basic skill. Exercise 3 (JSON grammar coverage) works well as an advanced assignment.',
    },
    '08-spec-mutation': {
        'Specification Mutation': 'This lecture is the final stop of the mutation series: shifting the mutation target from source code to specifications (predicates) and state machines (FSMs).',
        'Three-Lecture Comparison': 'Lecture #6 mutates programs; #7 mutates grammars; this lecture mutates specifications (predicates) and state machines (FSMs).',
        'What Is Specification Mutation': 'A specification mutant substitutes operators in a predicate. The test suite must distinguish the original specification from each mutant.',
        'Six Operators': 'AOR/ROR/LCR/MOR/AOD/COD are the six specification mutation operators. LCR (&&↔||) and ROR (>↔>=) are the most common.',
        'Example Categories: Basic vs. SMV': 'Basic operators directly replace operators; SMV (Safety Monitor Violation) operators are designed for safety-monitoring patterns.',
        'SMV Example Table': 'SMV is especially important in formal verification contexts, such as aerospace and automotive safety specifications.',
        'Example: (a || b) && c with 6 Operators': 'Have students compute the effect of each operator on this predicate by hand, then compare with the tool\'s mutant list.',
        'Kill Algorithm': 'Kill condition: the original predicate and the mutant predicate produce different outputs on some input. The test suite must include such an input.',
        'Safety Monitor FSM': 'FSM (finite state machine) is another form of specification. The tool shows side-by-side comparison of original and mutant FSMs.',
        'Why Memoryless': 'Most FSMs are memoryless (Markov property): the next state depends only on the current state and input, not on history.',
        'diff = killer set': 'The difference set (diff) of two FSMs is precisely the test set that kills the FSM mutant. The tool computes and displays this diff directly.',
        'Tool: Overview': 'Three sections: left for predicate input, middle for mutant list, right for side-by-side FSM view.',
        'Tool: Mutants and Score': 'The tool shows kill status for both predicate and FSM mutants, plus the overall mutation score.',
        'Tool: Side-by-Side FSM': 'The side-by-side view lets students directly see which state transition differs between original and mutant FSM.',
        'Tool: SMV Source': 'The tool shows the SMV-format specification, helping students understand how formal verification tools (like NuSMV) interpret these specs.',
        'Persistence': 'The tool saves the most recent predicate and FSM, enabling cross-session continuation of work.',
        'Algorithm Overview': 'Predicate mutation substitutes AST operators; FSM mutation adds/removes/changes state transition table entries; diff uses BFS.',
        'Connection to Other Chapters': 'Specification Mutation connects formal verification (§16) and Logic Coverage (§4–5). This is the most theory-heavy lecture in the series.',
        'Summary': 'Specification Mutation tests whether the specification itself is precise enough. A strong test suite should kill all non-equivalent specification mutants.',
        'Classroom Exercise': 'Exercise 1 (compute LCR mutants by hand) is the most basic. Exercise 3 (FSM diff) suits students with automata theory background.',
    },
    '09-fuzz-testing': {
        'Fuzz Testing': 'From this lecture, the series enters the "automated test generation" trilogy (Fuzz → Symbex → Concolic). Fuzz is the simplest but still highly effective method.',
        'Conceptual Positioning': 'Fuzz testing\'s key advantage: fully automated, no specification required, can find boundary cases hard to find through manual testing. Drawback: unpredictable coverage.',
        'When to Use Fuzz': 'Best for: systems accepting large volumes of external input (parsers, network protocols, file handlers). Less suitable for: bugs requiring specific semantic inputs.',
        'Three Fuzz Steps': 'This tool implements: generate random integer/boolean inputs → execute the target function → record crashes and branch traces.',
        'Technical Core: Branch Instrumentation': 'The tool "instruments" each if/while condition before execution, recording taken/not-taken into a branch trace array.',
        'From Trace to CFG Coverage': 'Branch traces correspond to CFG edges. The tool computes node coverage and edge coverage percentages.',
        'Six Built-in Examples': 'Six examples cover: simple arithmetic, boundary checks, recursion (fibonacci), string handling, loops, and multi-branch logic.',
        'Tool: Overview': 'Left side: code input and test count. Right side: test case list (pass/crash) and CFG view.',
        'Tool: Test Cases and CFG': 'Click a test case and the CFG highlights the nodes and edges visited in that run. Ask students to find "which branch has never been covered."',
        'Tool: Crash Detection': 'Crash = runtime exception. The tool shows crash rate and error messages to help locate issues.',
        'Random Input Strategy': 'Phase 1 uses pure random integers/booleans. Phase 2 mutates interesting seeds (crashes + novel branch patterns) using ±1, boundary values, and bitflip.',
        'Fundamental Limits of Fuzz': 'Pure random fuzz cannot handle "magic numbers" (specific constants needed to trigger certain branches). Concolic execution (#11) solves this.',
        'Common Pitfalls': 'High node coverage ≠ good testing: if assertions only check "no crash," fuzz cannot find logic errors.',
        'Algorithm': 'Instrumentation uses regex replacement of if/while conditions. Loops have an iteration limit (10,000) to prevent infinite loops.',
        'Summary': 'Fuzz is a "volume" strategy. Phase 2 mutation lets the tool explore boundaries missed by pure random testing.',
        'Classroom Exercise': 'Exercise 1 (observe crash rate) is the most intuitive. Exercise 3 (compare fuzz vs. random) works well as a discussion topic.',
        'Further Reading': 'AFL and libFuzzer are the most widely used fuzz tools in industry. Interested students can try running AFL on their own programs.',
    },
    '10-symbolic-execution': {
        'Symbolic Execution': 'Symbolic execution is the most "mathematical" method in this series: treating program inputs as symbols and using constraint solvers to find concrete inputs for every path.',
        'From Fuzz to Symbex': 'Fuzz is "blind trial"; symbex is "systematic analysis." Symbex guarantees finding inputs for every reachable path (if solvable).',
        'Three Things: env / pc / branches': 'Execution state = environment (symbolic variable values) + path condition (constraints to reach this point) + branch trace (which branches taken).',
        'Fork Mechanism': 'At each conditional branch, symbex "forks" into two execution states (true and false paths). This is the root of path explosion.',
        'Finding Witnesses: Bounded Brute Force': 'The tool uses bounded brute-force search ([-10, 10] integer grid) to find concrete values satisfying the path condition. Real symbex systems use SMT solvers (e.g., Z3).',
        'Why Infeasible Paths Matter': 'If a path\'s constraints are unsatisfiable (infeasible), no test case can reach that path — this itself is important test information.',
        'Four Built-in Examples': 'Four examples cover: simple conditionals, multi-branch, nested conditions, and paths with equality constraints.',
        'Tool: Overview': 'Left side: code input. Right side: path list (each path shows path condition, witness, infeasibility flag).',
        'Tool: Path List': 'Each path entry shows: path condition (formula), concrete witness (x=1, y=-3), execution result. Click a path to highlight the CFG.',
        'Tool: CFG Path Highlighting': 'Clicking a path entry highlights the corresponding node and edge sequence in purple. Have students confirm the path condition matches the CFG path.',
        'Path Explosion': 'Exponential path count is symbex\'s biggest challenge. The tool uses a depth limit (max paths) to avoid explosion, but real systems need more sophisticated strategies.',
        'Algorithm': 'The tool uses recursive DFS to unfold the AST, cloning execution state at each conditional branch, accumulating the path condition, then solving.',
        'Real Symbex System Differences': 'Real systems (KLEE, Angr, S2E) use Z3/Boolector SMT solvers and can handle integers, characters, pointers, and complex constraints.',
        'Summary': 'Symbex systematically covers all reachable paths but is limited by path explosion. Concolic (#11) is a hybrid strategy combining concrete execution with symbolic analysis.',
        'Classroom Exercise': 'Exercise 1 (manually trace path conditions) is the most important. Exercise 3 (infeasible paths) suits students with linear algebra background.',
        'Further Reading': 'KLEE is the most famous symbex tool. EXE is KLEE\'s predecessor. A&O §13 has a detailed introduction.',
    },
    '11-concolic-execution': {
        'Concolic Execution': 'Concolic = concrete + symbolic. Core idea: execute with concrete values, simultaneously track symbolic path conditions, then negate conditions to find new paths.',
        'Three-Lecture Comparison': 'Fuzz is fastest but blind; symbex is systematic but slow; concolic compromises: start with concrete execution, use symbex to guide the next input.',
        'Etymology': 'Concolic = concurrent symbolic + concrete. DART (2005) was the first paper to coin this term — worth mentioning historically.',
        'Four Core Steps (Per Iteration)': 'Each iteration: execute → collect path condition → negate the last unexplored branch → solve for new input. These four steps are the algorithm\'s heart.',
        '"Negate the Last Unexplored Branch"': '"Negate" means: take the negation of the last path condition constraint, then solve. This guarantees a different branch is taken in the next execution.',
        'Key Difference from Symbex': 'Symbex tracks all paths simultaneously (exponential space); concolic takes one path at a time (linear space), progressively exploring.',
        'Four Built-in Examples': 'The four examples match symbex, making it easy for students to compare how the two methods find witnesses differently.',
        'Tool: Overview + Settings': 'The "Seed Input" lets students control the starting point; "Max Iterations" controls exploration depth. Start with a small iteration count to observe behavior.',
        'Tool: Iteration List': 'Each iteration entry shows: concrete input, path condition, execution result, which branch was negated.',
        'Tool: CFG Synchronized Highlighting': 'Clicking an iteration entry synchronizes the CFG to highlight that iteration\'s path, letting students trace the exploration progress.',
        'Algorithm': 'The tool maintains both concrete values and symbolic expressions in an AST interpreter simultaneously, recording both at branch points.',
        'Path Convergence': 'Concolic does not guarantee finding all paths (limited by iteration count) but can explore many paths in a bounded number of steps — more systematic than pure fuzz.',
        'Real Systems vs. This Tool': 'Real systems (SAGE, DrChecker) use Z3 for constraint solving and can handle characters, memory addresses, and complex types. This tool uses integer brute-force for simplicity.',
        'Summary': 'Concolic is the best compromise between fuzz + symbex: starting from concrete execution, using symbolic analysis to guide the next step, avoiding path explosion.',
        'Classroom Exercise': 'Exercise 1 (trace iterations) is the most core understanding exercise. Exercise 3 (compare with fuzz) works well as a final discussion.',
        'Further Reading': 'The DART paper (Godefroid et al., 2005) is the founding work on concolic execution. SAGE is Microsoft\'s concolic tool for Windows fuzzing.',
    },
    '12-test-generation': {
        'Test Generation from Coverage': 'This lecture connects all previous criteria: using coverage criteria to generate the "minimum test set" covering "all requirements." The culminating application of the series.',
        'Position in the Series': 'Previous lectures "define criteria"; this lecture "automatically generates test sets satisfying criteria." The last mile from theory to engineering practice.',
        'Problem Definition': 'Problem: given a function and a coverage criterion, find the minimum set of test cases such that all criterion-required requirements are covered.',
        'Computation Pipeline': 'Pipeline: source code → CFG → coverage requirements → Greedy Set Cover → minimum test set → execution verification.',
        'Key Modules': 'Four modules work together: pathFinder, TestPathSelector (greedy), TestCaseBuilder (concretize), Runner (verify). Each has a clear role.',
        'Greedy Set Cover': 'Greedy Set Cover is an approximation for an NP-hard problem: each step picks the path covering the most uncovered requirements. Approximation ratio ln(n), usually excellent in practice.',
        'Eight Coverage Criteria': 'The tool supports NC/EC/ECC/PPC/ADUP/ADU/ADef + CACC. Have students switch criteria and observe how test set size changes.',
        'Tool: Overview': 'Left: code input. Right: three sections — requirements list, selected tests list, CFG view.',
        'Tool: Requirements Card': 'The requirements card lists all coverage requirements (node/edge/path/clause). Click a requirement to highlight the CFG and show which test covers it.',
        'Tool: Minimal Tests Card': 'The minimal tests card lists the Greedy Set Cover–selected minimum test set. Each test shows which requirements it covers.',
        'Tool: CFG Interaction': 'Clicking a requirement or test synchronizes the CFG to highlight related nodes/edges/paths, helping students build visual connections between criteria and program structure.',
        'Example: abs(x) + Edge Coverage': 'abs(x) is the simplest demo: only two edges, needing two tests (x>0 and x<=0).',
        'Example: triangle + Prime Path Coverage': 'Triangle has multiple prime paths, requiring a significantly larger test set than edge coverage. This illustrates the impact of criterion strength.',
        'Infeasible Requirements': 'Some requirements correspond to paths that are semantically unreachable (infeasible). The tool marks these in red and skips them.',
        'Difference from #10/#11': 'Symbex/Concolic use constraint solving to find inputs; this tool uses brute-force integer grid search. The former is more powerful; the latter is more intuitive.',
        'Design Highlights': 'The tool\'s core challenge: translating a coverage requirement (abstract path) into concrete input values (integer combinations).',
        'Summary': 'This lecture turns "defining criteria" into "automated generation." The goal: help students understand that coverage criteria are not just evaluation metrics but also specifications for generating tests.',
        'Classroom Exercise': 'Exercise 1 (observe test set sizes for different criteria) is the most intuitive. Exercise 3 (modify code and observe CFG/requirement changes) works as an interactive demo.',
        'Further Reading': 'A&O §8 has the complete Test Path theory. The Set Cover implementation is in src/utils/setCover.js.',
    },
    '13-logic-binding': {
        'Logic Coverage Binding': 'This lecture solves the "last mile" problem of Logic Coverage: mapping abstract clauses (a, b, c) to concrete program expressions so tests can actually be executed.',
        'The "Last Mile Gap"': 'Students can compute CACC requirement tables but don\'t know how to generate concrete inputs satisfying "a=T, b=F." Binding bridges this gap.',
        'Three-Layer Mapping': 'Three layers: criterion (CACC) → clause truth value combination (a=T, b=F) → concrete witness (x=1, y=10). Binding handles the second-to-third layer conversion.',
        'Binding Interface': 'The tool\'s Binding panel sits immediately below the logic coverage tool. After selecting a criterion, each requirement row shows a corresponding witness.',
        'Clause Binding Sub-panel': 'Each clause (a, b, c) has an input box where students enter a JavaScript expression (e.g., x > 0).',
        'Result Table Four Columns': 'Four columns: row number (which requirement), clause truth values (a=T, b=F, c=T), constraint formula ((x > 0) && !(y < 10)), witness (x=1, y=10).',
        'Solving Algorithm: Bounded Brute Force': 'The tool first tries an analytic solver (interval arithmetic); if that fails, it uses brute-force search over the [-10, 10] integer Cartesian product.',
        'Why Smallest Absolute Value Order': 'Searching from 0 upward in |x| order ensures the witness closest to 0 is found, making it easiest for students to verify by hand.',
        'Example: abs(x)': 'abs(x)\'s predicate is x >= 0, with one clause. Binding is straightforward: a=T → x=0, a=F → x=-1.',
        'Example: max(a, b)': 'max(a, b)\'s predicate is a >= b, one clause. CACC needs two witnesses: a=T and a=F.',
        'Example: triangle': 'Triangle has multiple clauses; CACC has more requirements. Have students verify each witness actually satisfies the corresponding clause truth values.',
        'Auto-fill': 'Auto-fill reads the selected example\'s defaultBindings and fills all clause expressions with one click. Use auto-fill to quickly see results, then manually modify to learn.',
        'Binding Tool Demo': 'Live demo: select triangle → select CACC → click auto-fill. Have students match each witness table row to the corresponding textbook requirement.',
        'Search Range Setting': 'Default search range is [-10, 10]. For expressions involving large numbers (e.g., x > 50), expand the range. The analytic solver (B1) handles this case exactly.',
        'Limitations and Future Work': 'Limitation: the tool can only find integer witnesses within the search range. The analytic interval solver (added in B1) handles simple linear constraints like x > 50 exactly.',
        'Summary': 'Binding turns Logic Coverage from "paper exercise" into "verifiable test inputs." Mastering this three-layer mapping is what it means to truly understand the engineering application of Logic Coverage.',
        'Classroom Exercise': 'Exercise 1 (manually fill bindings and verify witnesses) is the most important. Exercise 3 (expand search range) helps understand solver limitations.',
        'Further Reading': 'A&O §4–5 has the complete Logic Coverage theory. The binding solver implementation is in src/utils/logicBinding.js.',
    },
}

# Write the script output as a summary, then the actual content will be applied per file
for stem, notes in ZH.items():
    total = len(notes)
    print(f"ZH {stem}: {total} notes")
for stem, notes in EN.items():
    total = len(notes)
    print(f"EN {stem}: {total} notes")

# Actual injection function
def inject_notes(filepath, notes_dict, lang):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    # Split on slide separators. The first block is frontmatter.
    slides = content.split('\n---\n')
    result = []

    for i, slide in enumerate(slides):
        # Find the first heading in this slide block
        heading_match = None
        for line in slide.split('\n'):
            stripped = line.lstrip('#').strip()
            if line.startswith('#') and stripped:
                heading_match = stripped
                break

        # Find matching note
        note = None
        if heading_match:
            for key, val in notes_dict.items():
                if key in heading_match:
                    note = val if isinstance(val, str) else val
                    break

        # Append slide content
        slide_stripped = slide.rstrip()
        if note and i > 0:  # Don't add notes to frontmatter
            result.append(f"{slide_stripped}\n\n<!-- {note} -->")
        else:
            result.append(slide_stripped)

    new_content = '\n---\n'.join(result) + '\n'
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(new_content)
    return len([s for s in slides if s.strip()])

import os
base = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'docs', 'slides')

# Process ZH-TW files
for stem, notes in ZH.items():
    filepath = os.path.join(base, f"{stem}.zh-TW.md")
    if os.path.exists(filepath):
        count = inject_notes(filepath, notes, 'zh-TW')
        print(f"Processed {stem}.zh-TW.md — {count} slides")
    else:
        print(f"MISSING: {filepath}")

# Process EN files
for stem, notes in EN.items():
    filepath = os.path.join(base, f"{stem}.en.md")
    if os.path.exists(filepath):
        count = inject_notes(filepath, notes, 'en')
        print(f"Processed {stem}.en.md — {count} slides")
    else:
        print(f"MISSING: {filepath}")
PYEOF
